@extends('layouts.app')

@section('title', 'Admin Detail')

@php
    $initials = collect(explode(' ', trim($detail['name'])))->filter()->map(fn ($part) => strtoupper(substr($part, 0, 1)))->take(2)->implode('') ?: 'A';
@endphp

@section('content')
    <div class="iam-detail-page admin-detail">
        <div class="detail-hero"><div class="detail-hero-banner"></div><div class="detail-hero-body"><div class="detail-identity"><div class="detail-avatar-wrap"><div class="detail-avatar-xl avatar-admin-gradient">{{ $initials }}</div><div class="online-indicator"></div></div><div><div class="profile-name">{{ $detail['name'] }}</div><div class="profile-position">{{ str_replace('_', ' ', $detail['role']) }} - internal access profile</div><div class="badge-row"><span class="badge admin"><svg class="icon"><use href="/assets/icons/sprite.svg#icon-admin-and-moderator-accounts-svg"></use></svg>{{ str_replace('_', ' ', $detail['role']) }}</span><span class="badge active">{{ $detail['status'] }}</span><span class="badge senior">{{ $detail['mfa'] }} MFA</span></div></div></div><div class="detail-hero-actions"><a class="detail-btn" href="{{ route('admin.dashboard.iam.users', ['role' => $user->role]) }}"><svg class="icon"><use href="/assets/icons/sprite.svg#icon-back-to-account-penalty-and"></use></svg>Back</a><a class="detail-btn primary" href="{{ route('admin.dashboard.iam.user-security', $user) }}"><svg class="icon"><use href="/assets/icons/sprite.svg#icon-security-and-access-svg-viewbox-0"></use></svg>Security</a><button class="detail-btn danger" type="button" onclick="openDetailModal('freeze')"><svg class="icon"><use href="/assets/icons/sprite.svg#icon-account-penalty-and-freeze-3"></use></svg>Freeze</button></div></div></div>
        <div class="stat-strip columns-4"><div class="mini-stat"><div class="v">{{ $detail['mfa'] }}</div><div class="l">MFA</div></div><div class="mini-stat"><div class="v">{{ $detail['login_attempts'] }}</div><div class="l">Failed Logins</div></div><div class="mini-stat"><div class="v">{{ $detail['security']['active_sessions'] }}</div><div class="l">Sessions</div></div><div class="mini-stat"><div class="v">{{ $detail['security']['social_accounts'] }}</div><div class="l">Social Links</div></div></div>
        <div class="detail-grid">
            <div class="right-col"><div class="section-card"><div class="section-head"><div class="section-head-inner"><div class="section-icon"><svg class="icon"><use href="/assets/icons/sprite.svg#icon-admin-and-moderator-accounts-svg"></use></svg></div><div><div class="section-title">Internal Identity</div><div class="section-sub">Core administrator account data</div></div></div></div><div class="section-body"><div class="info-grid"><div class="info-item"><label>User ID</label><value>{{ $detail['id'] }}</value></div><div class="info-item"><label>Username</label><value>{{ $detail['username'] }}</value></div><div class="info-item"><label>Name</label><value>{{ $detail['name'] }}</value></div><div class="info-item"><label>Email</label><value>{{ $detail['email'] }}</value></div><div class="info-item"><label>Role</label><value>{{ str_replace('_', ' ', $detail['role']) }}</value></div><div class="info-item"><label>Locked Until</label><value>{{ $detail['locked_until'] }}</value></div></div></div></div><div class="section-card"><div class="section-head"><div class="section-head-inner"><div class="section-icon"><svg class="icon"><use href="/assets/icons/sprite.svg#icon-activity-log-svg-viewbox-0-0"></use></svg></div><div><div class="section-title">Review Workload</div><div class="section-sub">TODO: bind approvals and moderation queues when admin workload contract exists.</div></div></div></div><div class="section-body"><div class="activity-item"><div class="activity-icon"><svg class="icon"><use href="/assets/icons/sprite.svg#icon-verification-queue-and-sla-management-svg"></use></svg></div><div><div class="activity-text">Pending verifications, escalations, and operational decisions stay static until a queue data source is supplied.</div><div class="activity-time">TODO-safe workload boundary</div></div></div></div></div><div class="section-card"><div class="section-head"><div class="section-head-inner"><div class="section-icon"><svg class="icon"><use href="/assets/icons/sprite.svg#icon-activity-log-svg-viewbox-0-0"></use></svg></div><div><div class="section-title">Activity Timeline</div><div class="section-sub">Account events and system flags</div></div></div></div><div class="section-body"><div class="timeline">@forelse ($detail['activity']['feed'] as $activity)<div class="tl-item"><div class="tl-dot blue"></div><div><div class="tl-title">{{ str_replace('_', ' ', ucfirst($activity->activity_type)) }}</div><div class="tl-desc">Live activity feed record #{{ $activity->id }}</div><div class="tl-time">{{ \Illuminate\Support\Carbon::parse($activity->created_at)->format('M j, Y H:i') }}</div></div></div>@empty<div class="tl-item"><div class="tl-dot slate"></div><div><div class="tl-title">Account registered</div><div class="tl-desc">Static fallback until user_activity_feed records exist.</div><div class="tl-time">{{ $detail['joined'] }}</div></div></div>@endforelse</div></div></div></div>
            <div class="left-col"><div class="panel-card"><h3>Security Metrics</h3><div class="info-list"><div class="info-row"><span class="k">Last Login</span><span class="v">{{ $detail['last_login'] }}</span></div><div class="info-row"><span class="k">Latest IP</span><span class="v">{{ $detail['security']['latest_ip'] }}</span></div><div class="info-row"><span class="k">MFA State</span><span class="v">{{ $detail['mfa'] }}</span></div><div class="info-row"><span class="k">Account Status</span><span class="v">{{ $detail['status'] }}</span></div></div></div><div class="panel-card"><h3>Account Status Actions</h3><div class="admin-action-list billing-spaced">@foreach (['active' => 'Activate operator', 'suspended' => 'Suspend operator', 'frozen' => 'Freeze operator'] as $status => $label)<form method="POST" action="{{ route('admin.dashboard.iam.user-security.update', $user) }}">@csrf @method('PUT')<input type="hidden" name="role" value="admin"><input type="hidden" name="status" value="{{ $status }}"><input type="hidden" name="admin_note" value="Status changed from IAM admin detail view."><button class="admin-action-btn {{ $status === 'frozen' ? 'danger' : '' }}" type="submit">{{ $label }}</button></form>@endforeach</div></div><div class="panel-card"><h3>Admin Modal Surface</h3><p class="sub">Modal-ready summary for internal review actions.</p><div class="modal-preview billing-spaced"><strong>{{ $detail['name'] }}</strong><br><span>{{ str_replace('_', ' ', $detail['role']) }} - {{ $detail['status'] }} - {{ $detail['mfa'] }} MFA</span></div></div></div>
        </div>
    </div>
    <div class="modal-overlay" id="freezeModal"><div class="modal"><div class="modal-title">Freeze this account?</div><div class="modal-desc">{{ $detail['name'] }} will lose operator access until manually restored.</div><form method="POST" action="{{ route('admin.dashboard.iam.user-security.update', $user) }}">@csrf @method('PUT')<input type="hidden" name="role" value="admin"><input type="hidden" name="status" value="frozen"><textarea class="modal-textarea" name="admin_note">Frozen from IAM admin detail view.</textarea><div class="modal-actions"><button class="modal-cancel" type="button" onclick="closeDetailModal('freeze')">Cancel</button><button class="modal-confirm-danger" type="submit">Freeze Account</button></div></form></div></div><div class="toast-container" id="detailToastContainer"></div>
@endsection

@include('iam.users._detail-scripts')


