@extends('layouts.master')
@section('title', 'IAM Engineer Detail')
@section('content_header')
<div class="app-content-header"><div class="container-fluid"><div class="row align-items-center"><div class="col-sm-8"><h3 class="mb-0">Engineer / Member Profile</h3></div><div class="col-sm-4"><ol class="breadcrumb float-sm-end mb-0"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard.iam.users') }}">IAM</a></li><li class="breadcrumb-item active">{{ $detail['name'] }}</li></ol></div></div></div></div>
@endsection
@section('content')
<div class="app-content"><div class="container-fluid">
<a class="btn btn-outline-secondary mb-3" href="{{ route('admin.dashboard.iam.users') }}"><i class="bi bi-arrow-left me-1"></i>Back</a>
<div class="row g-3"><div class="col-lg-5"><div class="card h-100"><div class="card-header"><h3 class="card-title">Core Identity</h3></div><div class="card-body"><dl class="row mb-0"><dt class="col-sm-4">ID</dt><dd class="col-sm-8">{{ $detail['id'] }}</dd><dt class="col-sm-4">Name</dt><dd class="col-sm-8">{{ $detail['name'] }}</dd><dt class="col-sm-4">Email</dt><dd class="col-sm-8">{{ $detail['email'] }}</dd><dt class="col-sm-4">Role</dt><dd class="col-sm-8">{{ $detail['role'] }}</dd><dt class="col-sm-4">Verification</dt><dd class="col-sm-8">{{ $detail['verification'] }}</dd></dl></div></div></div><div class="col-lg-7"><div class="card h-100"><div class="card-header"><h3 class="card-title">Reputation & Contribution</h3></div><div class="card-body"><div class="row g-3"><div class="col-md-4"><div class="info-box"><span class="info-box-icon text-bg-primary"><i class="bi bi-star"></i></span><div class="info-box-content"><span class="info-box-text">Reputation</span><span class="info-box-number">{{ $detail['profile']->reputation_points ?? 0 }}</span></div></div></div><div class="col-md-4"><div class="info-box"><span class="info-box-icon text-bg-success"><i class="bi bi-robot"></i></span><div class="info-box-content"><span class="info-box-text">AI Usage</span><span class="info-box-number">{{ $detail['profile']->ai_usage_count ?? 0 }}</span></div></div></div><div class="col-md-4"><div class="info-box"><span class="info-box-icon text-bg-info"><i class="bi bi-search"></i></span><div class="info-box-content"><span class="info-box-text">Discoverable</span><span class="info-box-number">{{ ($detail['profile']->is_discoverable ?? false) ? 'Yes' : 'No' }}</span></div></div></div></div></div></div></div></div>
<div class="row g-3 mt-0"><div class="col-lg-4"><div class="card h-100"><div class="card-header"><h3 class="card-title">Professional Profile</h3></div><div class="card-body"><dl><dt>Specialization</dt><dd>{{ $detail['specialty'] }}</dd><dt>Experience</dt><dd>{{ $detail['experience'] }}</dd><dt>Company / Institution</dt><dd>{{ $detail['profile']->current_company ?? $detail['profile']->current_institution ?? 'No profile yet' }}</dd><dt>Position</dt><dd>{{ $detail['profile']->position ?? 'No profile yet' }}</dd></dl></div></div></div><div class="col-lg-4"><div class="card h-100"><div class="card-header"><h3 class="card-title">Privacy</h3></div><div class="card-body text-secondary">Profile privacy settings are displayed when profile records exist.</div></div></div><div class="col-lg-4"><div class="card h-100"><div class="card-header"><h3 class="card-title">Security Utilities</h3></div><div class="card-body"><dl><dt>MFA</dt><dd>{{ $detail['mfa'] }}</dd><dt>Last login</dt><dd>{{ $detail['last_login'] }}</dd><dt>Login attempts</dt><dd>{{ $detail['login_attempts'] }}</dd><dt>Locked until</dt><dd>{{ $detail['locked_until'] }}</dd></dl></div></div></div></div>
<div class="card mt-3"><div class="card-header"><h3 class="card-title">Activity / Audit / Penalties</h3></div><div class="card-body text-secondary">IAM account activity feeds are shown here when activity records exist.</div></div>
</div></div>
@endsection